name: AuthTG
version: '2.0'
main: org.ezhik.authTG.AuthTG
api-version: '1.20'
authors: [ Ezhik24 ]

commands:
  register:
    description: 'Регистрация'
    aliases:
      - reg
  login:
    description: 'Login'
    aliases:
      - l
  code:
    description: 'Code'