name: AuthTG
version: '2.0'
main: org.ezhik.authTG.AuthTG
api-version: '1.20'
authors: [Ezhik24, ABBAfan]
commands:
  register:
    description: 'Register'
    aliases:
      - reg
  login:
    description: 'Login'
    aliases:
      - l
  code:
    description: 'Code'
  mcbc:
    description: 'MCBC'
  tgbc:
    description: 'TGBC'
  changepassword:
    description: 'Change password'
    aliases:
      - cp
  setpassword:
    description: 'Set password'
  friend:
    description: 'Friends'
  setspawn:
    description: 'Set spawn'
  admin:
    description: 'AdminCMD'
  command:
    description: 'CommandCMD'
  kick:
    description: 'Kick player'
  mute:
    description: 'Mute player'
  ban:
    description: 'Ban player'