name: AuthTG
version: '2.5.1'
main: org.ezhik.authTG.AuthTG
api-version: '1.16'
authors: [Ezhik24, ABBAfan]
softdepend: ["PlaceholderAPI"]
commands:
  register:
    description: 'Register'
    aliases:
      - reg
  login:
    description: 'Login'
    aliases:
      - l
  authtg:
    description: 'AuthTGCMD'
  code:
    description: 'Code'
  mcbc:
    description: 'MCBC'
  tgbc:
    description: 'TGBC'
  changepassword:
    description: 'Change password'
    aliases:
      - cp
  setpassword:
    description: 'Set password'
  friend:
    description: 'Friends'
  setspawn:
    description: 'Set spawn'
  admin:
    description: 'AdminCMD'
  command:
    description: 'CommandCMD'
  kick:
    description: 'Kick player'
  mute:
    description: 'Mute player'
  ban:
    description: 'Ban player'
  unban:
    description: 'Unban player'
  unmute:
    description: 'Unmute player'
  logout:
    description: 'Logout'
  unlink:
    description: 'Unlink'